### ISSUE TITLE
Enhancements for extract to new note command

### ISSUE THREAD

**Issue by nixsee** [svsool/vscode-markdown-kit#1]
Nice work on this! A few things I'd love to see (and currently have in my own macro)

- Create a wiki link in the original page that points to the new one
- add a # heading to the page with the file name (or have a configurable heading/template in the settings, allowing for other data like date or a "---" separator to be added)
- option to close and/or return to the original note. I am often extracting many segments from one file into many new ones, so it is useful to return to the original note (as well as close the new ones so that they don't clutter the workspace)

Here's a quick GIF of what my macro does. I'm quite happy with it, but sometimes it is slow and has other little quirks. 

![ARh5TWQFt1](https://user-images.githubusercontent.com/24255237/90943030-56adee80-e3d5-11ea-864e-6e6371bda120.gif)

**Comment by svsool** [comment]
Hi,

Thanks for the ideas.

> Create a wiki link in the original page that points to the new one

I'm not sure if it should be a wiki link by default. Markdown link would probably be better since this extension is not only for use with Memo / Foam but also without them. In general, it would be good to make this configurable.

> add a # heading to the page with the file name (or have a configurable heading/template in the settings, allowing for other data like date or a "---" separator to be added)

Need to check if code [snippet](https://code.visualstudio.com/docs/editor/userdefinedsnippets) can be executed programmatically and custom [variables](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables) provided.

> option to close and/or return to the original note. I am often extracting many segments from one file into many new ones, so it is useful to return to the original note (as well as close the new ones so that they don't clutter the workspace)

I think returning / closing behavior can be made configurable as well.

**Comment by nixsee** [comment]
Awesome. Thanks for being so receptive to ideas!

**Comment by abuggin** [comment]
I opened [this](https://github.com/svsool/vscode-memo/issues/135) in the other repo, but I see it was an already requested feature. 
> Create a wiki link in the original page that points to the new one

this point is what I'm after. What kind of macro are you referring to @nixsee ?

**Comment by svsool** [comment]
Hi, I'm going to archive this repository and move functionality to [vscode-memo](https://github.com/svsool/vscode-memo) to ease maintenance a bit, discussion can be continued there if something. Thank you!
